version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    stdin_open: true
    tty: true 

  key_server:
    build: .
    volumes:
      - ./dev:/app
    environment:
      CONFIG: "/app/config/docker/Binary.toml"
    ports:
      - 1113:1113
    depends_on:
      - "mongodb"
    stdin_open: true
    tty: true 

  key_server_mutual_auth:
    build: .
    volumes:
      - ./dev:/app
    # The main difference for this service is the config file.
    # We'll override the entrypoint and pass a different config instead of
    # dealing with multiple Dockerfiles.
    environment:
      CONFIG: "/app/config/docker-mutual-auth/Binary.toml"
    ports:
      - 1114:1114
    depends_on:
      - "mongodb"
    stdin_open: true
    tty: true
