version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    container_name: nginx_tls
    restart: always
    ports:
      - 1115:1115
    depends_on:
      - "ks_nginx"
    volumes:
      - ./dev/config/nginx-tls/nginx.conf:/etc/nginx/nginx.conf
      - ./dev/test-pki/gen/certs/server.key:/etc/ssl/certs/server.key
      - ./dev/test-pki/gen/certs/server.chain:/etc/ssl/certs/server.crt

  key_server:
    build: .
    restart: always
    volumes:
      - ./dev:/app
    environment:
      CONFIG: "/app/config/docker/Binary.toml"
    ports:
      - 1113:1113
    healthcheck:
      test: "sh ./healthcheck.sh http://localhost:1113"
      interval: 10s
      timeout: 5s
    depends_on:
      - "mongodb"
    stdin_open: true
    tty: true 

  ks_client_auth:
    build: .
    restart: always
    volumes:
      - ./dev:/app
    environment:
      CONFIG: "/app/config/docker-client-auth/Binary.toml"
    ports:
      - 1114:1114
    healthcheck:
      test: "sh ./healthcheck.sh http://localhost:1114"
      interval: 10s
      timeout: 5s
    depends_on:
      - "mongodb"
    stdin_open: true
    tty: true

  ks_nginx:
    build: .
    volumes:
      - ./dev:/app
    environment:
      CONFIG: "/app/config/nginx-tls/Binary.toml"
    healthcheck:
      test: "sh ./healthcheck.sh http://localhost:1113"
      interval: 10s
      timeout: 5s
    depends_on:
      - "mongodb"
    stdin_open: true
    tty: true
