version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    stdin_open: true
    tty: true 

  key_server:
    build: .
    restart: always
    volumes:
      - ./dev:/app
    environment:
      CONFIG: "/app/config/docker/Binary.toml"
    ports:
      - 1113:1113
    healthcheck:
      test: "chmod +x healthcheck.sh && ./healthcheck.sh http://localhost:1113"
      interval: 10s
      timeout: 5s
    depends_on:
      - "mongodb"
    stdin_open: true
    tty: true 

  key_server_client_auth:
    build: .
    restart: always
    volumes:
      - ./dev:/app
    # The main difference for this service is the config file.
    # We'll override the entrypoint and pass a different config instead of
    # dealing with multiple Dockerfiles.
    environment:
      CONFIG: "/app/config/docker-client-auth/Binary.toml"
    ports:
      - 1114:1114
    healthcheck:
      test: "chmod +x healthcheck.sh && ./healthcheck.sh http://localhost:1114"
      interval: 10s
      timeout: 5s
    depends_on:
      - "mongodb"
    stdin_open: true
    tty: true
