version: '3.8'

services:

  postgres:
      build: ./persistence
      restart: always
      environment:
        # The container will create a postgres user with this name and password. We use these to connect to our DB.
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test_password
      ports:
        - "5432:5432"
      stdin_open: true
      tty: true

  key_server:
    build: .
    restart: always
    volumes:
      - ./dev:/app
    environment:
      CONFIG: "/app/config/docker/Binary.toml"
    ports:
      - 1113:1113
    healthcheck:
      test: "sh ./healthcheck.sh http://localhost:1113"
      interval: 10s
      timeout: 5s
    depends_on:
      - "postgres"
    stdin_open: true
    tty: true 
