[[service]]
address = "::1"
port = 1114
private_key = "dev/localhost.key"
certificate = "dev/localhost.crt"
opaque_path = "dev/opaque"
opaque_server_key = "dev/opaque/server_setup"

[[service]]
address = "127.0.0.1"
port = 1114
private_key = "dev/localhost.key"
certificate = "dev/localhost.crt"
opaque_path = "dev/opaque"
opaque_server_key = "dev/opaque/server_setup"

[database]
mongodb_uri = 'mongodb://localhost:27017'
db_name = 'lock-keeper-test-db'
