address = "127.0.0.1"
port = 1114
session_timeout = "60s"
opaque_path = "dev/opaque"
opaque_server_key = "dev/opaque/server_setup"

[tls_config]
private_key = "dev/test-pki/gen/certs/server.key"
remote_storage_key = "dev/remote-storage-key/gen/remote_storage.key"
certificate_chain = "dev/test-pki/gen/certs/server.chain"
client_auth = true

[database]
mongodb_uri = 'mongodb://localhost:27017'
db_name = 'lock-keeper-test-db'

[logging]
lock_keeper_logs_file_name = "dev/logs/server.log"
all_logs_file_name = "dev/logs/all.log"