address = "0.0.0.0"
port = 1113
opaque_path = "/app/opaque"
opaque_server_key = "/app/opaque/server_setup"
remote_storage_key = "/app/remote-storage-key/gen/remote_storage.key"
max_blob_size = 1024

[tls_config]
private_key = "/app/test-pki/gen/certs/server.key"
certificate_chain = "/app/test-pki/gen/certs/server.chain"
client_auth = false

[logging]
stdout_log_level = "INFO"

[logging.log_files]
lock_keeper_logs_file_name = "/app/logs/docker/server.log"
all_logs_file_name = "/app/logs/docker/all.log"
