[package]
name = "lock-keeper-client-cli"
version.workspace = true
edition = "2021"


[dependencies]
# Local dependencies
lock-keeper = { path = "../../lock-keeper" }
lock-keeper-client = { path = "../../lock-keeper-client" }

# Workspace dependencies
async-trait.workspace = true
clap.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-futures.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
zeroize.workspace = true

# Other dependencies
anyhow = "1"
hex = "0.4"
humantime = "2.1"
colored = "2.0"
