# This is for running the lock-keeper server locally with a dockerized instance of the postgres server.
# Default name and password as set by the docker-compose.yml postgres service.
username = 'test'
password = 'test_password'
address = 'localhost:5432'
db_name = 'test'
min_connections = 10
max_connections = 30
connection_retries = 5
connection_retry_delay = "5s"
connection_timeout = "3s"