address = "127.0.0.1"
port = 1113
opaque_path = "dev/opaque"
opaque_server_key = "dev/opaque/server_setup"
remote_storage_key = "dev/remote-storage-key/gen/remote_storage.key"
max_blob_size = 1024

[tls_config]
private_key = "dev/test-pki/gen/certs/server.key"
certificate_chain = "dev/test-pki/gen/certs/server.chain"
client_auth = false

[logging]
stdout_log_level = "INFO"
