username = 'test'
password = 'test_password'
address = 'localhost:5432'
db_name = 'test'
max_connections = 5
connection_retries = 5
connection_retry_delay = "5s"
connection_timeout = "3s"
session_expiration = "60s"