# This file is meant to be used with our `docker compose` instance of postgres, so both lock-keepr server and
# database are running on docker instances.
username = 'test'
password = 'test_password'
address = 'postgres:5432'
db_name = 'test'
min_connections = 10
max_connections = 30
connection_retries = 5
connection_retry_delay = "5s"
connection_timeout = "3s"