address = "0.0.0.0"
port = 1113
opaque_path = "/app/opaque"
opaque_server_key = "/app/opaque/server_setup"
remote_storage_key = "/app/remote-storage-key/gen/remote_storage.key"

[logging]
lock_keeper_logs_file_name = "/app/docker/logs/server.log"
all_logs_file_name = "/app/docker/logs/all.log"
