address = "0.0.0.0"
port = 1113
opaque_path = "/app/opaque"
opaque_server_key = "/app/opaque/server_setup"
remote_storage_key = "/app/remote-storage-key/gen/remote_storage.key"
release_toml_path = "./boltlabs-release.toml"
max_blob_size = 1024

[logging]
stdout_log_level = "INFO"

[logging.log_files]
lock_keeper_logs_file_name = "/app/logs/docker/server.log"
all_logs_file_name = "/app/logs/docker/all.log"
