[package]
name = "key-server-cli"
version.workspace = true
edition = "2021"

[dependencies]
# Local dependencies
lock-keeper = { version = "2.3.0", registry = "key-mgmt-registry" }
lock-keeper-key-server = { path = "../../lock-keeper-key-server" }
lock-keeper-postgres = { path = "../../persistence/lock-keeper-sql" }
lock-keeper-session-cache-sql = { path = "../../persistence/lock-keeper-session-cache-sql" }

# Workspace dependencies
clap.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-stream.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-futures.workspace = true
tracing-subscriber.workspace = true

# Other dependencies
base64 = "0.13"
tracing-appender = "0.2"
