# CI pipeline runs on PRs and for every commit on main
# Runs: rustfmt, Clippy, build, test, doctest, doc build
name: Rust

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      # Install nightly toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt

      # Install stable toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          default: true

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make

      - name: Run Tests
        run: cargo make ci
