# CI pipeline runs on PRs and for every commit on main
# Runs: rustfmt, Clippy, build, test, doctest, doc build
name: Rust

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      # Install Rust nightly toolchain
      # action repo is here https://github.com/dtolnay/rust-toolchain  
      - name: Install Rust toolchain nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt                

      # Install Rust toolchain
      # action repo is here https://github.com/dtolnay/rust-toolchain
      - name: Install Rust toolchain stable
        uses: dtolnay/rust-toolchain@1.70.0
        with:
          # Do NOT use `toolchain` input. It will cause the cargo version specified
          # above to be ignored!
          # toolchain: stable // Do NOT use.
          components: clippy

      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make

      - name: Run Tests
        run: cargo make ci
