name: E2E tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      # Ensure Rust is the latest version
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make

      - name: Start Server
        run: cargo make start-server-detached
          
      - name: Run end-to-end tests
        run: cargo make e2e

      - name: Run integration tests
        run: cargo make integration
