name: E2E tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # action repo is here https://github.com/dtolnay/rust-toolchain
      - name: Install Rust toolchain stable      
        uses: dtolnay/rust-toolchain@1.67
        with:
          toolchain: stable

      # tptodo: remove
      # - uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: 1.67

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make

      - name: Initialize certs and keys
        run: cargo make init

      - name: Start Server
        run: cargo make start
          
      - name: Run all tests
        run: cargo make all-tests
