address = "0.0.0.0"
port = 1113
session_timeout = "60s"
private_key = "/app/test-pki/gen/certs/server.key"
certificate_chain = "/app/test-pki/gen/certs/server.chain"
client_auth = false
opaque_path = "/app/opaque"
opaque_server_key = "/app/opaque/server_setup"

[database]
mongodb_uri = 'mongodb://mongodb:27017'
db_name = 'lock-keeper-test-db'
