address = "0.0.0.0"
port = 1114
session_timeout = "60s"
opaque_path = "/app/opaque"
opaque_server_key = "/app/opaque/server_setup"

[tls_config]
private_key = "/app/test-pki/gen/certs/server.key"
remote_storage_key = "/app/server-side-encryption/gen/remote_storage.key"
certificate_chain = "/app/test-pki/gen/certs/server.chain"
client_auth = true

[database]
mongodb_uri = 'mongodb://mongodb:27017'
db_name = 'lock-keeper-test-db'

[logging]
lock_keeper_logs_file_name = "/app/logs/server.log"
all_logs_file_name = "/app/logs/all.log"