[[service]]
address = "::"
port = 1113
private_key = "dev/localhost.key"
certificate = "dev/localhost.crt"
opaque_path = "dev/opaque"
opaque_server_key = "dev/opaque/server_setup"

[[service]]
address = "0.0.0.0"
port = 1113
private_key = "dev/localhost.key"
certificate = "dev/localhost.crt"
opaque_path = "dev/opaque"
opaque_server_key = "dev/opaque/server_setup"

[database]
mongodb_uri = 'mongodb://mongodb:27017'
db_name = 'lock-keeper-test-db'
